name: Build and Push Docker to Cloudsmith

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Cloudsmith
        uses: docker/login-action@v2
        with:
          registry: docker.cloudsmith.io
          username: token
          password: ${{ secrets.CLOUDSMITH_API_KEY }}

      - name: Build and Push Docker image
        run: |
          docker build -t docker.cloudsmith.io/basmarb/basmarb_rp/realestate-portal1:latest .
          docker push docker.cloudsmith.io/basmarb/basmarb_rp/realestate-portal1:latest

